#!/bin/bash  
# tomcat startup tomcat service 
# chkconfig: 2345 10 90  
# description: start and stop the tomcat daemon.  
# auther: vdevops
prog=tomcat
lockfile=/var/lock/subsys/$prog

TOMCAT_HOME=/usr/local/tomcat
TOMCAT_BIN=${TOMCAT_HOME}/bin  
TOMCAT_START=${TOMCAT_BIN}/startup.sh  
TOMCAT_STOP=${TOMCAT_BIN}/shutdown.sh  
# necessary environment variables export  
#JDK options
export JAVA_HOME=/usr/local/java
export PATH=$JAVA_HOME/bin:$PATH
export CLASS_PATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar
#
export CATALINA_BASE=/usr/local/tomcat
export PATH=$CATALINA_BASE/bin:$PATH
#export CATALINA_BASE PATH
  
# source function library.  
. /etc/rc.d/init.d/functions
  
if [ ! -f ${TOMCAT_BIN}/catalina.sh ];then
     echo "Tomcat not valilable !!!"  
     exit  
fi  

start(){  
        echo -n "Starting Tomcat ......Waiting...... "  
        daemon $TOMCAT_START  
        RETVAL=$?
        echo  
        [ $RETVAL -eq 0 ] && touch $lockfile
        return $RETVAL
       }  

stop(){  
        echo -n "Shutting down Tomcat... "  
        daemon $TOMCAT_STOP
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        return $RETVAL
        }  
restart(){  
       stop  
       start  
       }  
status(){  
       ps ax --width=1000 | grep "[o]rg.apache.catalina.startup.Bootstrap start" | awk '{printf $1 "\n"}' | wc -l > /var/log/tomcat_process_count 
       read line < /var/log/tomcat_process_count
       if [ $line -gt 0 ]; then  
            echo -n "tomcat ( pid "  
       ps ax --width=1000 | grep "[o]rg.apache.catalina.startup.Bootstrap start" | awk '{printf $1 " "}'  
            echo -n ") is running..."  
       echo  
       else  
           echo "Tomcat is stopped"  
      fi  
        }  
case "$1" in  
       start)  
             start ;;  
        stop)  
              stop ;;  
     restart)  
             stop  
            sleep 3  
             start ;;  
      status)  
            status ;;  
           *)  
            echo "Usage: tomcat {start|stop|restart|status}"  
            exit 1  
esac  
exit 0 
